householddata <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
householddata <- subset(householddata, (householddata$Date=="1/2/2007")|(householddata$Date=="2/2/2007"))
datetimeplot <- strptime(paste(householddata$Date,householddata$Time,sep = " "),"%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
par(mar=c(4,4,2,2))
plot(datetimeplot,householddata$Global_active_power,type = "l",ylab = "Global active power", xlab = "")
plot(datetimeplot,householddata$Voltage,type = "l",ylab = "Voltage", xlab = "datetime")
plot(datetimeplot,householddata$Sub_metering_1,type = "l",ylab = "Energy sub metering", xlab = "")
lines(datetimeplot,householddata$Sub_metering_2,col="red")
lines(datetimeplot,householddata$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = c(1,1,1), bty = "n")
plot(datetimeplot,householddata$Global_reactive_power,type = "l",ylab = "Global_reactive_power", xlab = "datetime")
dev.copy(png,file="plot4.png",height=480,width=480)
dev.off()