householddata <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
householddata <- subset(householddata, (householddata$Date=="1/2/2007")|(householddata$Date=="2/2/2007"))
datetimeplot <- strptime(paste(householddata$Date,householddata$Time,sep = " "),"%d/%m/%Y %H:%M:%S")
plot(datetimeplot,householddata$Global_active_power,type = "l",ylab = "Global Active Power (kilowatts)")
dev.copy(png,file="plot2.png",height=480,width=480)
dev.off()
