householddata <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
householddata <- subset(householddata, (householddata$Date=="1/2/2007")|(householddata$Date=="2/2/2007"))
datetimeplot <- strptime(paste(householddata$Date,householddata$Time,sep = " "),"%d/%m/%Y %H:%M:%S")
plot(datetimeplot,householddata$Sub_metering_1,type = "l",ylab = "Energy sub metering")
lines(datetimeplot,householddata$Sub_metering_2,col="red")
lines(datetimeplot,householddata$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = c(1,1,1))
dev.copy(png,file="plot3.png",height=480,width=480)
dev.off()